# Use the latest Alpine image
FROM alpine:latest

ENV NVM_DIR=/root/.nvm
RUN apk update && apk add --no-cache \
    bash \
    curl \
    git \
    bind-tools \        
    net-tools \         
    busybox-extras \
    tcpdump \
    tmux \
    tshark \
    vim && \ 
    mkdir -p $NVM_DIR && \
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash && \
    . $NVM_DIR/nvm.sh && nvm install 18

CMD ["/bin/bash"]
