apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: ws-debugger-deployment
  name: ws-debugger-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      run: ws-debugger-pod
  template:
    metadata:
      annotations:
        ad.datadoghq.com/ws-debugger-pod.logs: >-
          [{
            "source": "ws-debugger-pod",
            "service": "ws-conn-checker",
            "log_processing_rules": [{
              "type": "multi_line",
              "name": "log_start_with_date",
              "pattern" : "WebSocket connection closed"
            }]
          }]
      labels:
        run: ws-debugger-pod
    spec:
      containers:
      - command:
        - sleep
        - infinity
        image: moraesjeremias/net-tools-tbsh:v1.0.0
        imagePullPolicy: Always
        name: ws-net-tools-debugger
        resources:
          requests:
            cpu: 100m
            memory: 50Mi
          limits:
            cpu: 100m
            memory: 100Mi
        securityContext:
          privileged: true
      - image: moraesjeremias/ws-conn-checker:v0.0.2
        imagePullPolicy: Always
        name: ws-conn-checker
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
          limits:
            cpu: 100m
            memory: 200Mi
        env:
        - name: WS_SERVER
          value: <PLACEHOLDER>
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      imagePullSecrets:
      - name: availj
